// STATES ACTIONS
export const LOADING_DATA = "LOADING_DATA"
export const CLEAR_LOADING_DATA = "CLEAR_LOADING_DATA"
export const RESET_STATE = "RESET_STATE"
export const RESET_MODAL = "RESET_MODAL"
export const PAGE_NOT_FOUND = "PAGE_NOT_FOUND"

// ERRORS ACTIONS
export const GET_ERRORS = "GET_ERRORS"
export const CLEAR_ERRORS = "CLEAR_ERRORS"
export const GET_GEOLOCATION_ERRORS = "GET_GEOLOCATION_ERRORS"

// GLOBAL ACTIONS
export const MODAL_ON = "MODAL_ON"
export const MODAL_OFF = "MODAL_OFF"

// GEOLOCATION ACTIONS
export const GET_GEOLOCATION = "GET_GEOLOCATION"
